version: '3.9'

services:

  mongo:
    image: mongo:latest
    container_name: syn-app-db
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54.0
    container_name: syn-app-db-admin
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@syn-app-db:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
