version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: syn-app-db-prod
    restart: 'no'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${SYN_APP_DB}
    volumes:
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env.docker.prod

  app:
    container_name: syn-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${SYN_APP_DB}
      SYN_APP_CONTRACTS_COLLECTION: ${SYN_APP_CONTRACTS_COLLECTION}
    env_file:
      - .env.docker.prod
